services:
  db:
    image: postgres:15.9-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "irmin"
      POSTGRES_PASSWORD: "irmin"
      POSTGRES_DB: "graph-news"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  graph-news-service: 
    build:
      context: ./graph-news-backend
    container_name: graph-news-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      DATABASE_URL: jdbc:postgresql://db:5432/graph-news
      DATABASE_USER: irmin
      DATABASE_PASSWORD: irmin
      JWT_SECRET: c2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA
      JWT_EXPIRATION: 86400000

  web:
    build:
      context: ./graph-news-frontend
      args:
        - VITE_API_URL=http://localhost:8080
    container_name: web
    ports:
      - "5173:80"
    environment:
      NGINX_PORT: 80
volumes:
  pgdata: