name: Notify Discord on Events

on:
  push:
    branches:
      - main
      - '**' # Trigger for all branches
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  notify-discord-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Discord for Main Branch
        if: github.ref == 'refs/heads/main'
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🚀 **New commit on `main` branch!**
            **Repository:** ${{ github.repository }}
            **Commit Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **View Changes:** ${{ github.event.head_commit.url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord for Other Branches
        if: github.ref != 'refs/heads/main'
        uses: Ilshidur/action-discord@master
        with:
          args: |
            📝 **New commit on branch `${{ github.ref_name }}`**
            **Repository:** ${{ github.repository }}
            **Commit Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **View Changes:** ${{ github.event.head_commit.url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  notify-discord-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord on Pull Request Opened
        if: github.event.action == 'opened'
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🔥 **New Pull Request Opened!**
            **Repository:** ${{ github.repository }}
            **PR Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **View PR:** ${{ github.event.pull_request.html_url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Pull Request Synchronize (Updated)
        if: github.event.action == 'synchronize'
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🔄 **Pull Request Updated!**
            **Repository:** ${{ github.repository }}
            **PR Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **View PR:** ${{ github.event.pull_request.html_url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Pull Request Closed
        if: github.event.action == 'closed'
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ✅ **Pull Request Closed!**
            **Repository:** ${{ github.repository }}
            **PR Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Merged:** ${{ github.event.pull_request.merged }}
            **View PR:** ${{ github.event.pull_request.html_url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
